sudo: required
services: 
  - docker

before_install: 
  - docker build -t akshay174285/react-test -f /client/Dockerfile.dev ./client


script:
- docker run -e CI=true akshay174285/react-test npm run test


after_success:
  - docker build -t akshay174285/multi-client -f ./client
  - docker build -t akshay174285/multi-nginx -f ./ngnix
  - docker build -t akshay174285/multi-services -f ./server
  - docker build -t akshay174285/multi-worker -f ./worker
